src/util/api.js
Relates to https://github.com/HSLdevcom/hsl-map-generator-server/pull/18
=> Changed generateImage request body options

package.json, src/components/stopPoster/mapContainer.js, yarn.lock
So that we only show the dotted line once
=> Update map style

src/components/tramDiagram/tramDiagram.css
This was merged to master after the original PR removing the other variables
=> Fix variable

src/components/stopPoster/stopPoster.js
Fixes overflow error caused by decimal numbers in svg viewbox
=> Allow 1px overflow

scripts/generator.js, scripts/store.js, scripts/util/log.js, src/components/stopPoster/footer.js, src/index.js
A high priority PR that fixes the template images.
=> Fix issues related to the template configurator.

src/components/map/customMap.js, src/components/routeDiagram/routeDiagramContainer.js, src/components/stopPoster/stopPoster.css, src/components/stopPoster/stopPoster.js, src/util/routes.js
Fixes the overflow error caused by a static map image.
=> Fix route diagram overflow

package.json, src/components/map/customMap.js, src/components/routeDiagram/routeDiagramContainer.js, src/components/stopPoster/stopPoster.js, src/util/map.js, src/util/routes.js, src/util/tree.js
Since #183 will be merged when needed, I extracted some more generally useful fixes into another PR if we want to make posters with the zone SVG map before including the zone header.
I also tried to get the route diagram to stay visible for longer and now it has a max-height so that the poster doesn't think it's longer than it actually could be. It's not perfect, but should yield better results.
=> Layout priority

src/components/stopPoster/routes.css, src/components/timetable/simpleRoutes.js, src/components/timetable/tableHeader.css, src/components/timetable/timetable.css, src/components/timetable/timetable.js, src/styles/base.css
I noticed some layout discrepancies in the standalone timetable layout. This PR fixes those.
=> Fix timetable layout

README.md, src/components/stopPoster/stopPoster.js
=> Documentation

src/components/map/stopMap.js, src/components/map/stopMapContainer.js, src/components/map/stopSymbol.js
Lisätty laiturinumerot keskelle lähialuekartan pysäkkisymboleja. Numerot ottavat värinsä riippuen pysäkkisymbolin väreistä.
Testaus:
Checkout MM-212_laiturinumero
hsl-map-publisher käyntiin
=> 212-Laiturinumero lähialuekartalle

scripts/store.js
Value updates on status changes. It also updates on `build` -table when adding or removing posters.
=> Update updated_at -values on changes

src/components/map/mapImageContainer.js, src/util/apolloWrapper.js
Also some added linting fixes.
=> MM-418: Switch to joreDate parameter with generation date

src/components/stopPoster/stopPoster.js
(cherry picked from commit d0932d1335fc7c00911c6465bef0c9dd53908119)
=> Use tram diagram also on light rail stops

src/components/timetable/timetableContainer.js
Check StopPoster and Timetable works correctly
=> StopPoster timetables column fix

src/components/a3Timetable/a3Timetable.js, src/components/a3stopPoster/a3header.js
Fix generating errors when generating A3 StopPosters containing large amounts of routes.
=> #26236: Fix StopPosterA3 generating error

src/components/routeDiagram/destinations.js, src/components/routeDiagram/path.js, src/components/routeDiagram/routeDiagramContainer.js, src/components/routeDiagram/stop.js, src/util/routes.js
[AB#37395](https://dev.azure.com/hslfi/4611a8bb-62f5-4ff4-874b-746fd11cc599/_workitems/edit/37395): Pass color properties to routes from GraphQL
=> Fix trunk route color in route diagram

scripts/generator.js, src/components/lineTimetable/allStopsList.css, src/components/lineTimetable/allStopsList.js, src/components/lineTimetable/lineTableColumns.css, src/components/lineTimetable/lineTableColumns.js, src/components/lineTimetable/lineTableHeader.css, src/components/lineTimetable/lineTableHeader.js, src/components/lineTimetable/lineTimetable.css, src/components/lineTimetable/lineTimetable.js, src/components/lineTimetable/lineTimetableContainer.js, src/components/lineTimetable/lineTimetableHeader.css, src/components/lineTimetable/lineTimetableHeader.js, src/components/stopPoster/stopPoster.css, src/components/util.css, src/util/domain.js, test/testStops.js
This PR also includes possible hidden variants of given line (like with line 15) in same timetable, this might be changed though !
- Also added different layout when showing routes that don't have timed stops (for example 1016)
=> AB#32085: Show both directions in same timetable

scripts/util/createEmptyTemplate.js, src/components/routeDiagram/routeDiagram.css, src/components/stopPoster/footer.css, src/components/stopPoster/footer.js, src/components/stopPoster/terminalPoster.js
Terminal poster template changes to be tested in dev environment
=> AB#36691 terminal posters

.env.dev, .env.local, .env.prod, src/components/app.js
=> AB#62084 change sales point endpoint url

src/components/errorPage/errorPage.css, src/components/errorPage/errorPage.js, src/components/lineTimetable/lineTimetable.js, src/components/lineTimetable/lineTimetableContainer.js
Adds an error page that is shown to the user if the Line Timetable encounters an error during rendering.
=> AB#64706: Add LineTimetable error page
