src/util/apolloWrapper.js
This is done to make sure nested wrappers are added to the queue before
their parent wrapper is removed.
=> Update queue after rendering in apollo wrapper

package.json, yarn.lock
Fixes duplicate names in bilingual labels.
Depends on: HSLdevcom/hsl-map-style#27
=> Update map style dependency

src/util/map.js
Temporarily use the dev server for generating the poster map. This should probably not be pulled into the prod development.
=> Use dev server for generating the poster

Dockerfile, src/util/map.js, webpack.common.js, webpack.dev.js
Reads the API url for the map generation service from env. The production endpoint is set as default, but now that we're testing a new update to the generator server it is convenient to be able to set the url from the docker-compose file. This PR enables that.
=> Server url from env

src/components/app.js, src/components/timetable/tableHeader.css, src/components/timetable/tableRows.css, src/components/timetable/timetable.css, src/components/timetable/timetable.js, src/components/timetable/timetableContainer.js
Same goal as PR #177 but implemented with em units to make all elements resize in uniform based on one font-size value.
em values are calculated from a base of 16, which is what the timetable root element will have when not in standalone mode.
=> Larger font size for printed timetables.

src/components/routeDiagram/routeDiagram.css, src/components/tramDiagram/tramDiagram.css
My IDE messed up the refactoring when I renamed a CSS class in the standalone timetable PR, and renamed everywhere it found that name. Here is the fix that renames unrelated classes back to what they were.
=> Fix ide renaming mess.

src/components/timetable/timetable.css
Small css change to remove page changes in the printable timetable sheets
=> timetable page break removed

src/components/stopPoster/stopPoster.js, src/util/routes.js
RouteDiagram was missing from most of the posters in production. I assume this problem is due to the programs inability to calculate the correct height in which it should render the route diagram. This often led to the program generating a route diagram that was too big, and therefore removed due to overflow. This PR is a fast fix to get the route diagrams back in to production, and therefore this branch is now (9.5.2019) deployed into production.
This is however not a viable solution, since this "fix" only seems to work when there is a svg, and no lähikartta. This is not a problem for this batch, but is certainly something that needs to be fixed before merging to master.
=> DO NOT MERGE: Bruteforce finding suitable route diagram

README.md, src/util/map.js
To test the error throwing you need to have generator-server running locally and have changes in ```server.js``` so that ```/generateImage``` returns status 500. E.g change line 109 to ```processResult = false;```.
It would probably also be wise to test in dev by generating big set of posters so there might actually be "real" cases when the generator-server fails to deliver map and the publisher backend throws errors.
=> Improved errors with map

migrations/20191216105850_poster_order.js, scripts/server.js, scripts/store.js
It is important to preserve the order of the posters in the concatenated file. This has become a problem since we started to use multiple instances of the server and storing the files in Azure, as they would be downloaded in a random order.
This PR adds an `order` column to the poster table which stores the order in which the posters where submitted from the UI. The UI has had ordering logic for a while. When downloading the generated posters and concatenating them, the posters are reordered according to the associated order number from the database.
=> Preserve poster order

src/components/stopPoster/stopPoster.js
Adding the conditional makes it so checking for the horizontal overflow starts after first change to components
=> 164 horizontal overflow fix

.github/workflows/buildAndPublish_dev.yml, .github/workflows/buildAndPublish_prod.yml
Configure github actions to deploy to Docker Hub such that:
"Dev" tag is built and deployed when a pull request is made to production
"Production" tag is built and deployed when a merge (push) is made to production
=> MM-230: Configure github actions

.github/workflows/buildAndPublish_dev.yml, .github/workflows/buildAndPublish_prod.yml
This version of the workflows creates the timestamp and short commit hash, adds them into a tag and pushes to docker hub along with the regular 'dev' or 'prod' image push.
=> MM-265: Timestamped docker images

.github/dependabot.yml
Set target branch to development so we can actually properly test and validate dependabot PRs.
=> MM-334 - Configure dependabot PR target branch

README.md, constants.js, package.json, scripts/generator.js, scripts/server.js, yarn.lock
Check readme for new start commands (Docker)
To test:
make a POST request to the ```/generateRenderUrl``` endpoint of the publisher-server
Example parameters for request body:
```JSON
"props": {
"stopId": "1010109",
"date": "2023-05-03",
"isSummerTimetable": false,
"printTimetablesAsA4": true,
"printTimetablesAsGreyscale": false,
"template": "default"
}
```
The endpoint should return with HTTP 200 and provide the render URL in the body of the response. Open that in your browser (if running locally check for docker container naming vs. localhost in the hostname !) and you should see the timetable rendered within seconds.
=> MM-497: Endpoint for render URL generation, Update README about service splitting

src/components/stopPoster/routes.css, src/components/stopPoster/routes.js
This allow rendering to continue and not to fail if the route title is too long.
=> Allow route title to enter the padding area

README.md, package.json, scripts/generator.js, src/components/timetable/timetable.css, src/components/timetable/timetable.js, src/components/timetable/timetableContainer.js, yarn.lock
- Add current date by default unless date is included in generateRenderUrl params
- Added parameter to hide address info from the output (Visible by default)
- Added parameter to add a print button into the output (Hidden by default)
HOW TO TEST:
Spin up the local dev environment and include `showAddressInfo` and `showPrintButton` boolean parameters with the endpoint query
=> MM-502: Add more functionality to generateRenderUrl endpoint and rendering

src/components/timetable/tableRows.js
How to test:
- Clone
- Start local instance as usual
Open timetable generation url for stop ID that previously showed departures every hour on weekends:
http://localhost:5000/?component=Timetable&props%5BstopId%5D=6300204&props%5Bdate%5D=2023-08-17&props%5BisSummerTimetable%5D=true&props%5BdateBegin%5D=&props%5BdateEnd%5D=&props%5BprintTimetablesAsA4%5D=false&props%5BprintTimetablesAsGreyscale%5D=false
=> MM-522: Fix single departure grouping with same minutes

src/components/timetable/timetable.js, src/components/timetable/timetableContainer.js
Timetable rendering API now accepts `lang` parameter with `fi`, `sv` and `en` as options for changing the print button language.
=> #26114: language change for print button

src/components/map/stopLabel.js
Grouped routeIds also have their trunkroute boolean properties with them, making them distinquishable from actual trunkroutes grouped with the same destination.
=> AB#33201: Fix wrong route color in StopPoster

scripts/server.js, src/components/app.js, src/components/lineTimetable/allStopsList.css, src/components/lineTimetable/allStopsList.js, src/components/lineTimetable/lineTableColumns.css, src/components/lineTimetable/lineTableColumns.js, src/components/lineTimetable/lineTableHeader.css, src/components/lineTimetable/lineTableHeader.js, src/components/lineTimetable/lineTimetable.css, src/components/lineTimetable/lineTimetable.js, src/components/lineTimetable/lineTimetableContainer.js, src/components/lineTimetable/lineTimetableHeader.css, src/components/lineTimetable/lineTimetableHeader.js, src/components/timetable/timetableContainer.js, test/testStops.js
Test url on local `docker compose` setup:
http://localhost:5000/?component=LineTimetable&props%5BlineId%5D=2015&props%5BrouteDirection%5D=1&props%5BdateBegin%5D=1999-02-02&props%5BdateEnd%5D=2050-12-31&props%5Bdate%5D=2024-03-07
=> AB#32085: weekly line timetable

compose.yaml
Exposed the `.env.local` file for Docker compose to allow access to `DIGITRANSIT_APIKEY` locally without extra commands during build.
=> AB#33966: Expose local env file in compose

scripts/server.js
´/generateRenderUrl` endpoint will now return LineTimetable URLs too.
=> AB#32085: Refactor generateRenderUrl endpoint

src/util/domain.js
Refactor route filtering to compare both routeId and routeIdParsed, as well as use a comma as a delimiter in the filter string.
=> AB#46862: Refactor route filtering logic

src/components/map/stopMapContainer.js
The line breaks inside the string template caused the `bounded` parameter to be dropped from the URL, resulting in weird behavior.
=> AB#54863: Fix broken URL in string template resulting in unbound query

src/components/app.js, src/components/stopRoutePlate/stopRoutePlate.js, src/components/stopRoutePlate/stopRoutePlateContainer.js
This PR adds another Higher Order Component (HOC) onto the same `StopRoutePlate` component that gets rendered upon providing the `useLineQuery` boolean query param. Omitting the parameter or providing `useLineQuery=false` will instead render the basic `StopRoutePlate` component.
=> AB#57920: Add line query input option for StopRoutePlate

scripts/server.js, src/components/lineTimetable/lineTimetableContainer.js, src/util/domain.js
This PR refactors the line query logic for LineTimetables, so that it returns the Lines more broadly, practically merging line letter variants under the "main" line in the rendered timetables. 
This addresses the issues that were faced regarding some of the letter variants being under their main line and some of them being their own lines.
=> AB#64927: Refactor LineTimetable Line handling
